# Generated by Django 4.1.1 on 2022-11-08 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('subtitulo', models.CharField(max_length=30, null=True)),
                ('texto', models.CharField(max_length=1000)),
                ('fecha', models.DateField(null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBlog.autor')),
            ],
        ),
    ]
