# Generated by Django 4.1.1 on 2022-11-05 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seccion',
        ),
    ]
