# Generated by Django 4.1.1 on 2022-11-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_seccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto'),
        ),
    ]
