# Generated by Django 4.1.1 on 2022-11-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_pagina_foto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seccion',
        ),
        migrations.AlterModelOptions(
            name='autor',
            options={},
        ),
    ]
