# Generated by Django 4.1.1 on 2022-11-06 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0002_messages_remitente_alter_messages_destinatario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='mensajes',
            new_name='mensaje',
        ),
    ]
